[build]
target = "thumbv8m.main-none-eabihf"

[target.thumbv8m.main-none-eabihf]
rustflags = ["-Clink-arg=-Tlink.x", "-Ctarget-cpu=cortex-m33"]

[target.thumbv8m.main-none-eabi]
rustflags = ["-Clink-arg=-Tlink.x"]